name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
    - name: Xcode Select
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app
    - name: Xcode Versions
      run: xcodebuild -version -sdk
    - name: Build and Test
      run: xcodebuild -workspace LolayFundamenta.xcworkspace -scheme LolayFundamenta -sdk iphoneos16.2 -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" clean build test | xcpretty
